# Generated by Django 4.0.5 on 2022-06-20 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='user',
            name='date_filled_up',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 6, 34, 12, 367779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datebirth',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 6, 34, 12, 367779, tzinfo=utc)),
        ),
    ]
