# Generated by Django 4.0.5 on 2022-06-20 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_pub_date_user_date_filled_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='datebirth',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 6, 50, 18, 303812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_filled_up',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 6, 50, 18, 303812, tzinfo=utc)),
        ),
    ]
