# Generated by Django 4.0.5 on 2022-06-20 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_date_filled_up_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_filled_up',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 7, 29, 11, 499140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 7, 29, 11, 499140, tzinfo=utc)),
        ),
    ]
